# Generated by Django 5.0.4 on 2024-05-03 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='123456789', max_length=11)),
                ('pickupAddress', models.CharField(default='enter pickup Address', max_length=200)),
                ('wallet', models.IntegerField(default=0)),
                ('transferOption', models.CharField(choices=[('smart wallet', 'smart wallet'), ('bank Transfer', 'bank Transfer')], max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
