# Generated by Django 5.0.4 on 2024-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='pickupAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='transferOption',
            field=models.CharField(choices=[('bank Transfer', 'bank Transfer'), ('smart wallet', 'smart wallet')], max_length=100, null=True),
        ),
    ]
