# Generated by Django 5.0.4 on 2024-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_phone_alter_user_pickupaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transferOption',
            field=models.CharField(choices=[('smart wallet', 'smart wallet'), ('bank Transfer', 'bank Transfer')], max_length=100, null=True),
        ),
    ]
