# Generated by Django 5.0.4 on 2024-05-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_transferoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupRequest',
        ),
    ]
