# Generated by Django 5.0.4 on 2024-05-15 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_delete_pickuprequest'),
        ('order', '0010_alter_order_shipper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='AppUser',
        ),
    ]
