# Generated by Django 5.0.4 on 2024-05-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fees',
        ),
    ]
