# Generated by Django 5.0.4 on 2024-05-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_income',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
